Add graph display to index page.
bchendev/Spring2021-Team11 pull request #21
Opened 2021-03-20 20:19 UTC by abellegesse03

-> Also removed unused code.
![Screenshot (22)](https://user-images.githubusercontent.com/70480389/111884414-f0ec0a00-8997-11eb-912f-426b75d1b332.png)
![Screenshot (23)](https://user-images.githubusercontent.com/70480389/111884415-f0ec0a00-8997-11eb-9949-387c6ff15ec0.png)

2021-03-20 21:16 UTC, saka01 approved these changes

2021-03-21 00:31 UTC, FluffySheep requested changes
Please copy and paste the format from 

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAwhADgTwCcBLAcwAsYMAmABgEYBODAcQglIBs4MAZXrAB0o6Yej7EwCAM5wAJhgCuUOXEIYY5HgEFcAQzBaJUqLIA0GAGprpxaDQB0tDAApNPQSF6SZcTwEoAbjFMfAhFDABbPXwMKAgqRVkNcmJpDAAzYm4MOAAPKVwqYigMSEjcTmI9KCkMAHdiTRSebxNZBxCMAE1wqJiMCAAjGD0SjD0yvFiIDJbjXwmYEK6MNYxKGFxpJHR6-Yc9fUM4BwhCUlQq9rhpVF4ASSwAUQA5AGVngFpqJxWRTAAVSg3Gk6UIcAAjopiBCFENYkdKpI9EMcpw9PVBuo9KQIfINBAMON6iQYCVSBZpLMYPU9BCunI0jASENFPAFMpVOp3AtTDw0hgmdIWcQ2RzBqUahhPNp3hgHu9PBgAEJyxVmLoAdQeABUABIAeUBuowWu0ACULdpXrqHs95YaLdhDa8ACJ6h6ux0AMQwNu6GAA0g93RY4E0tOp8rgIWDscSKlV5J0ARh3nAeLy2osMud5tJcHAwMQsmAMBioKRFLieKQIAA3NRQCkYIuESJpWzQdI1ORdKqd0bkntKFRqeY5-mp4TCescbgOQz0mDSBycCB6OQuADkYEUhAhsB3FmAO+OAGta9Id0gANp787F8grk8YHdVKBwHcAXQAvkEc7sFwpzLoQq4OLIMCGlAvCbnIWB6JwnBDAYF4uHIhCYlgL7gYBUBiAAVIR2AQno8C9mUuFUH2ExyHI6RNIS8z6KQpwYIRqDCBkyhgCOpSYdh1EuP4GDAMIayQKYVByORkwALxxHAWLziBDgNmkNZVAAXuRdhQA4bpybqqLcCJwSlEKcmHPROCcIokRQLuUAOUMahvjuurEJE374WssmjDZCEQPZjnOa57kWDuAAKJBSDufnrElAV6EFFoQPU0guHeElJesd60BYtA-hY+X0BY9DFaVGB3tQFjUAAzCVax3g1FUAOzNS1AAsFUABxdXeACsFiMCVuV5TVABsFX0F1NXtfVnWlXefUWA1TUrYwFjdVVLWVet1DNXe9DlRgDVDeNlmTSddXnXtJ1tRgu3HfQvXPUdFgnSNz3LTV9Azc93WvYtz0DZq115Sda0YENn3-dtsPA19dA7fDtVnUNl0o3dQ1TcdjUWENy0TVD1DvVND3UD9Q1U4DcME6DQ1zSjMPdWNKOI0Nm2k0lrWFbD2M1Q1Z2U8dDV3VNLPC09Q0c8LFPoxdFhTdjvP5Q1gNTUrTPg8LMNY+LiNS8du0q8jNXdaLauQ3z3WS5tltPVN+Nfd1FN-Xe3U-VN8te1rfvdaD7VVerPUw+16PsyrevDQLLvHczKtC8Nkue9zFgh1dk0tUN73tdLw0-ZHieA+1jvDcHKdDRHD1yzH2c53elPm8dUsqw92vJ23zue1NFOx6rKsc2H01l53wfo1NEcp77Fh9cVo8-vhuVSSKgxFPp6SKeJkM7uSMDcLe76Ee8MAQGAF7pvgkRDCFGD6mocCESepM7o0ciaLeTC0IVb9aGQSgt5aZ-wImApK5BtB5DSEgMSo81gH24LAzy3lvwQxzusDcpB3hgCQnAWBGQkLmFHn+dB6wGxQJgXA226xEH4PfLFHwr8aFrCwTgvBBCiFwDIZNPMHZyLIP3IeBAYB8A7lJqQ0ekANyEB2DVHcABiPQcMC7dQ8go2gjAC4NT6r+XKf4LKrx7FQMCVBFJfhUsBRcGlpBaWILpfiDhvBfhwiuFw6s5AXwcggGADg2IwGeNwHysAVT4AeNuPcB4mwAH1TEJUSqYhwgl6gYTkhYPA-FpD4T-CAMwIAMlb2QKAekhAMrRXpDIZAIAkJ0nwNIXJIAhhYUvnAGA7xjgUmQCyRQ3CQBwFvvIVQcheA1GrLWH05xogwHJFWKpeh2QQAaZQSInAtSpAoscOAGZTBNGIBpGA+AqkijijABpJRZDgViriaIyBCGcHMCAAAVtIPIKpmkXlae8PQPlnFwFuVwvJzy8jvApNwAAiooBIfykB3IefoWRagqkZA3PUBpsYSgwC1MQT+5BkALzybGCAsgtRYVwFU2Mtw1BNgadCKFsU8D1JQHoaQXwvzyHkA0iE0JYRwCuaQG5MKAUgFkJ2LphAel5NsFWcFkL4BiolSAUYQwsU4uQHVRVWFsgUhwJEAVfTpBDQaUkOAJkhiMthb0hsPSHjjlgDgkgRRtAqDPvgbg-z7lwD-H+IAA

2021-03-21 01:39 UTC, abellegesse03 commented
After copying the code in from the link you posted, when I try to push my code, it gives me the following error:
![image](https://user-images.githubusercontent.com/70480389/111890943-a634b700-89c4-11eb-8b70-cdf87c7b8b77.png)
Is it because I'm not doing it on another new branch? Or am I doing something weird?

2021-03-22 02:04 UTC, saka01 commented
I think you might need to create a new branch and then commit to it, thats what I did, but it was weird because it added the one that caused this error and the one you commit when you create a new branch.

2021-03-22 03:14 UTC, FluffySheep approved these changes

2021-03-22 03:16 UTC, merged