Saka stocks on refresh
bchendev/Spring2021-Team11 pull request #29
Opened 2021-04-04 06:57 UTC by saka01

![image](https://user-images.githubusercontent.com/20563330/113501213-87b8da80-94f1-11eb-9aa6-bc67e5653183.png)

2021-04-04 18:36 UTC, abellegesse03 approved these changes

2021-04-04 23:09 UTC, FluffySheep requested changes

2021-04-04 23:09 UTC, FluffySheep commented on web/src/main/webapp/script.js
> +var my2d = [];
Minor: Please format this code in prettier.io https://github.com/bchendev/Spring2021-Team11/wiki/Code-Formatting

2021-04-05 01:57 UTC, FluffySheep approved these changes

2021-04-05 01:58 UTC, merged